# Site settings
title: muumu.us
description: >
    muumu.us
author: Kyle Johnston
email: kylerjohnston@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muumu.us" # the base hostname & protocol for your site
github_username:  kylerjohnston
exclude:
  - org/
  - LICENSE
  - push_to_s3.sh
  - Rakefile
  - Gemfile*
  - forspell.dict

# Build settings
#include: [_pages]
markdown: kramdown
permalink: /:categories/:title/
sass:
    style: compressed
