# Site settings
title: muumu.us
description: >
    muumu.us
author: Kyle Johnston
email: kylerjohnston@gmail.com
baseurl: "" 
url: "https://muumu.us" # the base hostname & protocol for your site
github_username:  kylerjohnston
exclude:
  - org/
  - LICENSE
  - push_to_s3.sh
  - Rakefile
  - Gemfile*
  - forspell.dict

include: [_pages]

jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    category: '/tag/:name/'

# plugins
plugins:
  - jekyll-archives

# Build settings
#include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title/
sass:
    style: compressed
