name: Build, test, push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'
          bundler-cache: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: bundle install
      - name: build
        run: bundle exec jekyll build
      - name: Run tests
        run: bundle exec rake test
        if: github.event_name == 'pull_request'
      - name: Deploy
        if: github.event_name == 'push'
        run: |
          aws s3 sync --delete _site/ s3://muumu.us
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DISTRO_ID }} --paths "/*"
