name: Build, test, push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: bundle install
      - name: build
        run: bundle exec jekyll build
      - name: Run tests
        run: bundle exec rake test
        if: github.event_name == 'pull_request'
      - name: Deploy
        run: bundle exec rake publish
        if: github.event_name == 'push'
