name: Test, build, and deploy Jekyll site to S3

on:
  push:
    branches:
      - master

jobs:
  build_site:
    name: Build, test, and to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and test
        run: bundle exec rake test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync --delete _site/ s3://muumu.us

      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id E1JLIALKAS239T --paths "/*"
